// Original code for onnx_runner.mqh
...
// Various lines of code preserving structure and logic
...
m_model_handle = OnnxCreate(model_path);
...
if(!OnnxRun(m_model_handle, input_matrix, output_matrix))
...